import type { Task } from './tasks.types';

export const taskRows: readonly Task[] = [
  {
    id: 1,
    title: 'Set up project scaffolding',
    status: 'Done',
    priority: 'High',
    assignee: 'Alice Chen',
    dueDate: '2026-04-01',
    estimatedHours: 8,
    completedHours: 7,
    tags: ['setup', 'devops'],
    description: 'Initialize repo, configure tooling and CI pipeline.',
    isBlocked: false,
  },
  {
    id: 2,
    title: 'Design database schema',
    status: 'Done',
    priority: 'Critical',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-05',
    estimatedHours: 12,
    completedHours: 14,
    tags: ['database', 'architecture'],
    description: 'Define tables, relations and migration strategy.',
    isBlocked: false,
  },
  {
    id: 3,
    title: 'Implement authentication flow',
    status: 'In Review',
    priority: 'Critical',
    assignee: 'Alice Chen',
    dueDate: '2026-04-15',
    estimatedHours: 16,
    completedHours: 16,
    tags: ['auth', 'security'],
    description: 'JWT-based login, refresh tokens and password reset.',
    isBlocked: false,
  },
  {
    id: 4,
    title: 'Build REST API endpoints',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-20',
    estimatedHours: 20,
    completedHours: 11,
    tags: ['api', 'backend'],
    description: 'CRUD endpoints for tasks, users and projects resources.',
    isBlocked: false,
  },
  {
    id: 5,
    title: 'Create data grid component',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-04-22',
    estimatedHours: 10,
    completedHours: 6,
    tags: ['frontend', 'ui'],
    description: 'Sortable, filterable data grid with column resizing.',
    isBlocked: false,
  },
  {
    id: 6,
    title: 'Write unit tests for API',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-28',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['testing', 'backend'],
    description: 'Jest test suites covering all API endpoints and edge cases.',
    isBlocked: false,
  },
  {
    id: 7,
    title: 'Integrate analytics dashboard',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-03',
    estimatedHours: 18,
    completedHours: 0,
    tags: ['analytics', 'frontend'],
    description: 'Charts and KPIs for project progress and team velocity.',
    isBlocked: true,
  },
  {
    id: 8,
    title: 'Performance optimisation',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-10',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['performance', 'backend'],
    description: 'Query optimisation, caching layer and load testing.',
    isBlocked: false,
  },
  {
    id: 9,
    title: 'Accessibility audit',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-05-12',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['a11y', 'frontend'],
    description: 'WCAG 2.1 AA compliance review and keyboard navigation fixes.',
    isBlocked: false,
  },
  {
    id: 10,
    title: 'Deploy to production',
    status: 'Cancelled',
    priority: 'Critical',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-30',
    estimatedHours: 6,
    completedHours: 0,
    tags: ['devops', 'release'],
    description: 'Blocked pending security sign-off; rescheduled to next sprint.',
    isBlocked: true,
  },
  {
    id: 11,
    title: 'Set up error monitoring',
    status: 'Done',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-08',
    estimatedHours: 4,
    completedHours: 4,
    tags: ['monitoring', 'devops'],
    description: 'Integrate Sentry for frontend and backend error tracking.',
    isBlocked: false,
  },
  {
    id: 12,
    title: 'Configure CDN for static assets',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-09',
    estimatedHours: 5,
    completedHours: 5,
    tags: ['devops', 'performance'],
    description: 'Route static files through CloudFront with proper cache headers.',
    isBlocked: false,
  },
  {
    id: 13,
    title: 'Design onboarding flow',
    status: 'In Review',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-04-18',
    estimatedHours: 12,
    completedHours: 12,
    tags: ['ux', 'frontend'],
    description: 'Multi-step wizard guiding new users through account setup.',
    isBlocked: false,
  },
  {
    id: 14,
    title: 'Implement role-based access control',
    status: 'In Progress',
    priority: 'Critical',
    assignee: 'Alice Chen',
    dueDate: '2026-04-25',
    estimatedHours: 18,
    completedHours: 9,
    tags: ['auth', 'security', 'backend'],
    description: 'Admin, manager and member roles with permission guards.',
    isBlocked: false,
  },
  {
    id: 15,
    title: 'Create email notification service',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-26',
    estimatedHours: 10,
    completedHours: 4,
    tags: ['email', 'backend'],
    description: 'Transactional emails via SendGrid for key user events.',
    isBlocked: false,
  },
  {
    id: 16,
    title: 'Write E2E tests with Playwright',
    status: 'Todo',
    priority: 'High',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-05',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['testing', 'frontend'],
    description: 'Cover critical user journeys: login, task CRUD, dashboard.',
    isBlocked: false,
  },
  {
    id: 17,
    title: 'Refactor legacy payment module',
    status: 'Todo',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-06',
    estimatedHours: 16,
    completedHours: 0,
    tags: ['payments', 'backend', 'refactor'],
    description: 'Migrate from Stripe v2 to v3 SDK with idempotency keys.',
    isBlocked: true,
  },
  {
    id: 18,
    title: 'Add dark mode support',
    status: 'Done',
    priority: 'Low',
    assignee: 'Diana Patel',
    dueDate: '2026-04-12',
    estimatedHours: 6,
    completedHours: 7,
    tags: ['ui', 'frontend'],
    description: 'CSS variable-based dark theme toggled via class on html element.',
    isBlocked: false,
  },
  {
    id: 19,
    title: 'Implement search functionality',
    status: 'In Review',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-22',
    estimatedHours: 14,
    completedHours: 14,
    tags: ['search', 'backend', 'frontend'],
    description: 'Full-text search with Postgres tsvector and ranked results.',
    isBlocked: false,
  },
  {
    id: 20,
    title: 'Set up staging environment',
    status: 'Done',
    priority: 'Critical',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-10',
    estimatedHours: 8,
    completedHours: 9,
    tags: ['devops', 'infrastructure'],
    description: 'Mirror production environment on a separate subdomain for QA.',
    isBlocked: false,
  },
  {
    id: 21,
    title: 'Implement file upload service',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-05-01',
    estimatedHours: 12,
    completedHours: 5,
    tags: ['storage', 'backend'],
    description: 'S3-backed file uploads with presigned URLs and virus scanning.',
    isBlocked: false,
  },
  {
    id: 22,
    title: 'Build team management UI',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-08',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['ui', 'frontend'],
    description: 'Invite, remove and assign roles to team members.',
    isBlocked: false,
  },
  {
    id: 23,
    title: 'Add rate limiting middleware',
    status: 'Done',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-14',
    estimatedHours: 4,
    completedHours: 4,
    tags: ['security', 'backend'],
    description: 'Per-IP and per-user rate limits with Redis sliding window.',
    isBlocked: false,
  },
  {
    id: 24,
    title: 'Create audit log system',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-14',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['logging', 'backend', 'compliance'],
    description: 'Record all write actions with actor, timestamp and diff.',
    isBlocked: false,
  },
  {
    id: 25,
    title: 'Optimise image delivery pipeline',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Diana Patel',
    dueDate: '2026-05-18',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['performance', 'frontend'],
    description: 'WebP conversion, lazy loading and responsive srcset generation.',
    isBlocked: false,
  },
  {
    id: 26,
    title: 'Integrate Stripe billing',
    status: 'In Progress',
    priority: 'Critical',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-02',
    estimatedHours: 22,
    completedHours: 10,
    tags: ['payments', 'backend'],
    description: 'Subscription plans, usage metering and invoice generation.',
    isBlocked: false,
  },
  {
    id: 27,
    title: 'Write API documentation',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-05-04',
    estimatedHours: 10,
    completedHours: 3,
    tags: ['docs', 'api'],
    description: 'OpenAPI 3.1 spec with examples for all public endpoints.',
    isBlocked: false,
  },
  {
    id: 28,
    title: 'Add multi-language support',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-20',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['i18n', 'frontend'],
    description: 'i18next integration with English and Spanish locale files.',
    isBlocked: false,
  },
  {
    id: 29,
    title: 'Implement webhook delivery system',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-15',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['webhooks', 'backend'],
    description: 'Retry logic, signing secrets and delivery log for outbound webhooks.',
    isBlocked: false,
  },
  {
    id: 30,
    title: 'Build notification centre',
    status: 'In Review',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-04-28',
    estimatedHours: 16,
    completedHours: 16,
    tags: ['ui', 'frontend', 'realtime'],
    description: 'In-app bell icon with unread badge and notification list.',
    isBlocked: false,
  },
  {
    id: 31,
    title: 'Set up GraphQL API layer',
    status: 'Cancelled',
    priority: 'High',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-20',
    estimatedHours: 24,
    completedHours: 6,
    tags: ['api', 'backend', 'graphql'],
    description: 'Cancelled in favour of REST + tRPC approach after team vote.',
    isBlocked: false,
  },
  {
    id: 32,
    title: 'Implement CSV export',
    status: 'Done',
    priority: 'Low',
    assignee: 'Alice Chen',
    dueDate: '2026-04-16',
    estimatedHours: 4,
    completedHours: 4,
    tags: ['export', 'frontend'],
    description: 'Download task list as CSV with selected column filtering.',
    isBlocked: false,
  },
  {
    id: 33,
    title: 'Configure log aggregation',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-13',
    estimatedHours: 6,
    completedHours: 6,
    tags: ['logging', 'devops'],
    description: 'Ship application logs to Datadog with structured JSON format.',
    isBlocked: false,
  },
  {
    id: 34,
    title: 'Create mobile-responsive layouts',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-05-07',
    estimatedHours: 18,
    completedHours: 8,
    tags: ['ui', 'frontend', 'mobile'],
    description: 'Breakpoint-driven layouts from 320px to 1440px viewports.',
    isBlocked: false,
  },
  {
    id: 35,
    title: 'Implement two-factor authentication',
    status: 'Todo',
    priority: 'Critical',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-09',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['auth', 'security'],
    description: 'TOTP-based 2FA with QR code setup and backup codes.',
    isBlocked: false,
  },
  {
    id: 36,
    title: 'Build comment thread system',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-06',
    estimatedHours: 16,
    completedHours: 7,
    tags: ['collaboration', 'backend', 'frontend'],
    description: 'Nested comments on tasks with @mentions and reactions.',
    isBlocked: false,
  },
  {
    id: 37,
    title: 'Migrate to Postgres 16',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-22',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['database', 'infrastructure'],
    description: 'In-place upgrade with downtime window and rollback plan.',
    isBlocked: false,
  },
  {
    id: 38,
    title: 'Add keyboard shortcut system',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Alice Chen',
    dueDate: '2026-05-25',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['ux', 'frontend', 'a11y'],
    description: 'Global hotkeys for navigation and task actions via hotkeys-js.',
    isBlocked: false,
  },
  {
    id: 39,
    title: 'Implement SSO with SAML',
    status: 'Todo',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-16',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['auth', 'enterprise', 'security'],
    description: 'SAML 2.0 identity provider integration for enterprise customers.',
    isBlocked: true,
  },
  {
    id: 40,
    title: 'Set up feature flag system',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-17',
    estimatedHours: 6,
    completedHours: 6,
    tags: ['infrastructure', 'devops'],
    description: 'LaunchDarkly integration with React SDK for gradual rollouts.',
    isBlocked: false,
  },
  {
    id: 41,
    title: 'Build project timeline view',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-28',
    estimatedHours: 22,
    completedHours: 0,
    tags: ['frontend', 'ui', 'gantt'],
    description: 'Gantt-style timeline with drag-to-resize task bars.',
    isBlocked: false,
  },
  {
    id: 42,
    title: 'Implement data backup jobs',
    status: 'In Review',
    priority: 'Critical',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-29',
    estimatedHours: 10,
    completedHours: 10,
    tags: ['database', 'devops', 'reliability'],
    description: 'Nightly encrypted S3 backups with 30-day retention policy.',
    isBlocked: false,
  },
  {
    id: 43,
    title: 'Create user activity feed',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Alice Chen',
    dueDate: '2026-06-01',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['frontend', 'ui'],
    description: 'Paginated activity log showing recent actions across projects.',
    isBlocked: false,
  },
  {
    id: 44,
    title: 'Add drag-and-drop task ordering',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-13',
    estimatedHours: 10,
    completedHours: 4,
    tags: ['frontend', 'ux'],
    description: 'DnD Kit-based reordering within and across status columns.',
    isBlocked: false,
  },
  {
    id: 45,
    title: 'Implement read receipts',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Carlos Silva',
    dueDate: '2026-06-05',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['collaboration', 'backend'],
    description: 'Track and display which team members viewed each task.',
    isBlocked: false,
  },
  {
    id: 46,
    title: 'Configure auto-scaling policies',
    status: 'Done',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-19',
    estimatedHours: 6,
    completedHours: 7,
    tags: ['infrastructure', 'devops'],
    description: 'ECS service auto-scaling based on CPU and request count metrics.',
    isBlocked: false,
  },
  {
    id: 47,
    title: 'Build settings and preferences page',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-11',
    estimatedHours: 12,
    completedHours: 5,
    tags: ['frontend', 'ui'],
    description: 'User preferences: timezone, notifications, theme, and language.',
    isBlocked: false,
  },
  {
    id: 48,
    title: 'Implement real-time collaboration',
    status: 'Todo',
    priority: 'High',
    assignee: 'Alice Chen',
    dueDate: '2026-05-30',
    estimatedHours: 30,
    completedHours: 0,
    tags: ['realtime', 'websockets', 'backend'],
    description: 'WebSocket-based live updates using Yjs CRDT for conflict resolution.',
    isBlocked: true,
  },
  {
    id: 49,
    title: 'Add print-friendly stylesheet',
    status: 'Done',
    priority: 'Low',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-21',
    estimatedHours: 3,
    completedHours: 3,
    tags: ['frontend', 'ui'],
    description: 'Print media query that hides nav and formats content for A4.',
    isBlocked: false,
  },
  {
    id: 50,
    title: 'Create API key management',
    status: 'In Review',
    priority: 'High',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-30',
    estimatedHours: 12,
    completedHours: 12,
    tags: ['api', 'security', 'backend'],
    description: 'Generate, revoke and scope API keys for programmatic access.',
    isBlocked: false,
  },
  {
    id: 51,
    title: 'Write migration scripts',
    status: 'Done',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-04-07',
    estimatedHours: 8,
    completedHours: 9,
    tags: ['database', 'devops'],
    description: 'Flyway-managed SQL migrations for each schema change.',
    isBlocked: false,
  },
  {
    id: 52,
    title: 'Build kanban board view',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-05-19',
    estimatedHours: 20,
    completedHours: 9,
    tags: ['frontend', 'ui'],
    description: 'Column-based task board with WIP limits and swimlanes.',
    isBlocked: false,
  },
  {
    id: 53,
    title: 'Add Slack integration',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-06-03',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['integration', 'notifications'],
    description: 'Post task updates to Slack channels via OAuth app and webhooks.',
    isBlocked: false,
  },
  {
    id: 54,
    title: 'Implement soft delete for tasks',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-23',
    estimatedHours: 5,
    completedHours: 5,
    tags: ['backend', 'database'],
    description: 'Archive flag with deleted_at timestamp and restore endpoint.',
    isBlocked: false,
  },
  {
    id: 55,
    title: 'Create custom report builder',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Carlos Silva',
    dueDate: '2026-06-10',
    estimatedHours: 24,
    completedHours: 0,
    tags: ['analytics', 'frontend'],
    description: 'Drag-and-drop report canvas with chart and table widgets.',
    isBlocked: false,
  },
  {
    id: 56,
    title: 'Harden Content Security Policy',
    status: 'In Review',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-02',
    estimatedHours: 8,
    completedHours: 8,
    tags: ['security', 'frontend'],
    description: 'Strict CSP headers with nonce-based inline script allowlist.',
    isBlocked: false,
  },
  {
    id: 57,
    title: 'Build bulk task actions',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-15',
    estimatedHours: 10,
    completedHours: 3,
    tags: ['frontend', 'ux'],
    description: 'Multi-select with bulk assign, status change and delete actions.',
    isBlocked: false,
  },
  {
    id: 58,
    title: 'Add GDPR data export',
    status: 'Todo',
    priority: 'High',
    assignee: 'Alice Chen',
    dueDate: '2026-05-24',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['compliance', 'backend'],
    description: 'Generate downloadable ZIP of all user data on request.',
    isBlocked: false,
  },
  {
    id: 59,
    title: 'Implement task dependencies',
    status: 'Todo',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-27',
    estimatedHours: 18,
    completedHours: 0,
    tags: ['backend', 'frontend'],
    description: 'Block/blocked-by relationships with cycle detection.',
    isBlocked: false,
  },
  {
    id: 60,
    title: 'Create PDF report export',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Carlos Silva',
    dueDate: '2026-06-12',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['export', 'backend'],
    description: 'Server-side PDF generation with Puppeteer from report templates.',
    isBlocked: false,
  },
  {
    id: 61,
    title: 'Set up blue-green deployment',
    status: 'Todo',
    priority: 'Critical',
    assignee: 'Bob Martinez',
    dueDate: '2026-06-02',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['devops', 'infrastructure'],
    description: 'Zero-downtime deployments with health checks and instant rollback.',
    isBlocked: false,
  },
  {
    id: 62,
    title: 'Add time tracking feature',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-05-21',
    estimatedHours: 16,
    completedHours: 6,
    tags: ['frontend', 'backend', 'tracking'],
    description: 'Start/stop timer per task with manual entry and weekly summary.',
    isBlocked: false,
  },
  {
    id: 63,
    title: 'Implement custom field types',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-06-08',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['frontend', 'backend'],
    description: 'User-defined fields: text, number, date, select, multi-select.',
    isBlocked: true,
  },
  {
    id: 64,
    title: 'Build API usage dashboard',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Eve Johnson',
    dueDate: '2026-06-15',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['analytics', 'frontend'],
    description: 'Per-key request counts, latency histograms and quota indicators.',
    isBlocked: false,
  },
  {
    id: 65,
    title: 'Migrate CSS to Tailwind v4',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-24',
    estimatedHours: 12,
    completedHours: 11,
    tags: ['frontend', 'refactor'],
    description: 'Replace custom CSS with Tailwind v4 utilities and CSS variables.',
    isBlocked: false,
  },
  {
    id: 66,
    title: 'Implement guest user mode',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Bob Martinez',
    dueDate: '2026-06-18',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['auth', 'frontend'],
    description: 'Read-only access for external reviewers via shareable links.',
    isBlocked: false,
  },
  {
    id: 67,
    title: 'Add data validation layer',
    status: 'In Review',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-05-05',
    estimatedHours: 10,
    completedHours: 10,
    tags: ['backend', 'validation'],
    description: 'Zod schemas for all API inputs with detailed error messages.',
    isBlocked: false,
  },
  {
    id: 68,
    title: 'Create project templates',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-06-06',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['frontend', 'backend'],
    description: 'Predefined task sets for common project types like sprint and launch.',
    isBlocked: false,
  },
  {
    id: 69,
    title: 'Implement task recurring schedules',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-06-09',
    estimatedHours: 16,
    completedHours: 0,
    tags: ['backend', 'scheduling'],
    description: 'Cron-based auto-creation of repeating tasks with RRULE support.',
    isBlocked: false,
  },
  {
    id: 70,
    title: 'Upgrade Node.js to v22',
    status: 'Done',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-04-26',
    estimatedHours: 4,
    completedHours: 4,
    tags: ['devops', 'infrastructure'],
    description: 'Update runtime and audit all native addons for compatibility.',
    isBlocked: false,
  },
  {
    id: 71,
    title: 'Build public status page',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Bob Martinez',
    dueDate: '2026-06-20',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['frontend', 'reliability'],
    description: 'Real-time uptime and incident history page at status subdomain.',
    isBlocked: false,
  },
  {
    id: 72,
    title: 'Add multi-project support',
    status: 'In Progress',
    priority: 'Critical',
    assignee: 'Diana Patel',
    dueDate: '2026-05-26',
    estimatedHours: 28,
    completedHours: 12,
    tags: ['backend', 'frontend', 'architecture'],
    description: 'Workspace-level multi-project isolation with cross-project search.',
    isBlocked: false,
  },
  {
    id: 73,
    title: 'Write load testing suite',
    status: 'Todo',
    priority: 'High',
    assignee: 'Alice Chen',
    dueDate: '2026-06-04',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['testing', 'performance'],
    description: 'k6 scenarios simulating 1000 concurrent users on critical paths.',
    isBlocked: false,
  },
  {
    id: 74,
    title: 'Integrate GitHub Actions CI',
    status: 'Done',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-06',
    estimatedHours: 6,
    completedHours: 6,
    tags: ['devops', 'ci'],
    description: 'Lint, test and build pipeline on every pull request.',
    isBlocked: false,
  },
  {
    id: 75,
    title: 'Create onboarding checklist widget',
    status: 'In Review',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-08',
    estimatedHours: 8,
    completedHours: 8,
    tags: ['frontend', 'ux'],
    description: 'Dismissible checklist guiding users to their first 5 actions.',
    isBlocked: false,
  },
  {
    id: 76,
    title: 'Add task label system',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-17',
    estimatedHours: 10,
    completedHours: 4,
    tags: ['frontend', 'backend'],
    description: 'Colour-coded labels with filter support in list and board views.',
    isBlocked: false,
  },
  {
    id: 77,
    title: 'Implement SSR for marketing pages',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-06-14',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['frontend', 'seo'],
    description: 'Next.js SSR for landing, pricing and blog for improved SEO.',
    isBlocked: false,
  },
  {
    id: 78,
    title: 'Build mention notification system',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-06-11',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['backend', 'notifications'],
    description: 'Parse @mentions in comments and send in-app and email alerts.',
    isBlocked: false,
  },
  {
    id: 79,
    title: 'Migrate to tRPC',
    status: 'Cancelled',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-05',
    estimatedHours: 30,
    completedHours: 8,
    tags: ['api', 'backend', 'refactor'],
    description: 'Cancelled — REST API meets current needs; revisit in Q3.',
    isBlocked: false,
  },
  {
    id: 80,
    title: 'Implement custom dashboards',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-06-16',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['frontend', 'analytics'],
    description: 'User-configurable dashboard with drag-and-drop widget placement.',
    isBlocked: false,
  },
  {
    id: 81,
    title: 'Add OAuth social login',
    status: 'In Review',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-05-09',
    estimatedHours: 12,
    completedHours: 12,
    tags: ['auth', 'frontend', 'backend'],
    description: 'Google and GitHub OAuth 2.0 with account linking support.',
    isBlocked: false,
  },
  {
    id: 82,
    title: 'Build project archive feature',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Diana Patel',
    dueDate: '2026-06-22',
    estimatedHours: 6,
    completedHours: 0,
    tags: ['backend', 'frontend'],
    description: 'Move completed projects to a searchable archive with restore.',
    isBlocked: false,
  },
  {
    id: 83,
    title: 'Implement smart task suggestions',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Alice Chen',
    dueDate: '2026-07-01',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['ai', 'backend'],
    description: 'LLM-powered task title and description autocomplete.',
    isBlocked: true,
  },
  {
    id: 84,
    title: 'Set up infrastructure as code',
    status: 'Done',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-04-11',
    estimatedHours: 10,
    completedHours: 11,
    tags: ['devops', 'infrastructure'],
    description: 'Terraform modules for VPC, ECS, RDS and S3 resources.',
    isBlocked: false,
  },
  {
    id: 85,
    title: 'Create developer sandbox environment',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-23',
    estimatedHours: 8,
    completedHours: 3,
    tags: ['devops', 'developer-experience'],
    description: 'One-command local stack via Docker Compose with seed data.',
    isBlocked: false,
  },
  {
    id: 86,
    title: 'Add sprint planning view',
    status: 'Todo',
    priority: 'High',
    assignee: 'Bob Martinez',
    dueDate: '2026-06-07',
    estimatedHours: 18,
    completedHours: 0,
    tags: ['frontend', 'planning'],
    description: 'Sprint backlog, velocity chart and capacity planning per team.',
    isBlocked: false,
  },
  {
    id: 87,
    title: 'Implement content moderation',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Diana Patel',
    dueDate: '2026-06-17',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['backend', 'safety'],
    description: 'Flag offensive content in comments using OpenAI Moderation API.',
    isBlocked: false,
  },
  {
    id: 88,
    title: 'Build workspace billing portal',
    status: 'In Progress',
    priority: 'Critical',
    assignee: 'Alice Chen',
    dueDate: '2026-05-29',
    estimatedHours: 16,
    completedHours: 7,
    tags: ['payments', 'frontend'],
    description: 'Stripe Customer Portal embedded for plan changes and invoices.',
    isBlocked: false,
  },
  {
    id: 89,
    title: 'Add custom status workflow',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Eve Johnson',
    dueDate: '2026-06-19',
    estimatedHours: 14,
    completedHours: 0,
    tags: ['backend', 'frontend'],
    description: 'Per-project configurable status columns with transition rules.',
    isBlocked: false,
  },
  {
    id: 90,
    title: 'Create integration test harness',
    status: 'In Progress',
    priority: 'High',
    assignee: 'Carlos Silva',
    dueDate: '2026-05-31',
    estimatedHours: 14,
    completedHours: 5,
    tags: ['testing', 'backend'],
    description: 'Shared test fixtures and database factory helpers for integration tests.',
    isBlocked: false,
  },
  {
    id: 91,
    title: 'Implement activity heatmap',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Bob Martinez',
    dueDate: '2026-06-25',
    estimatedHours: 10,
    completedHours: 0,
    tags: ['analytics', 'frontend'],
    description: 'GitHub-style contribution grid showing task completion over time.',
    isBlocked: false,
  },
  {
    id: 92,
    title: 'Build dependency graph visualiser',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Diana Patel',
    dueDate: '2026-06-28',
    estimatedHours: 16,
    completedHours: 0,
    tags: ['frontend', 'visualisation'],
    description: 'D3-based directed graph showing task dependency relationships.',
    isBlocked: true,
  },
  {
    id: 93,
    title: 'Add changelog and release notes',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Alice Chen',
    dueDate: '2026-06-30',
    estimatedHours: 6,
    completedHours: 0,
    tags: ['docs', 'frontend'],
    description: 'In-app modal showing latest release notes on version bump.',
    isBlocked: false,
  },
  {
    id: 94,
    title: 'Implement workspace usage quotas',
    status: 'In Review',
    priority: 'Critical',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-20',
    estimatedHours: 14,
    completedHours: 14,
    tags: ['backend', 'billing'],
    description: 'Enforce per-plan limits on seats, projects and storage.',
    isBlocked: false,
  },
  {
    id: 95,
    title: 'Create API changelog',
    status: 'Todo',
    priority: 'Low',
    assignee: 'Carlos Silva',
    dueDate: '2026-07-04',
    estimatedHours: 4,
    completedHours: 0,
    tags: ['docs', 'api'],
    description: 'Public-facing versioned changelog for breaking and non-breaking changes.',
    isBlocked: false,
  },
  {
    id: 96,
    title: 'Build AI meeting summary feature',
    status: 'Todo',
    priority: 'Medium',
    assignee: 'Bob Martinez',
    dueDate: '2026-07-08',
    estimatedHours: 18,
    completedHours: 0,
    tags: ['ai', 'backend', 'integration'],
    description: 'Transcribe and summarise meeting recordings into linked tasks.',
    isBlocked: true,
  },
  {
    id: 97,
    title: 'Implement workspace data residency',
    status: 'Todo',
    priority: 'High',
    assignee: 'Diana Patel',
    dueDate: '2026-07-10',
    estimatedHours: 24,
    completedHours: 0,
    tags: ['infrastructure', 'compliance'],
    description: 'EU and US region isolation for enterprise data residency requirements.',
    isBlocked: false,
  },
  {
    id: 98,
    title: 'Add browser push notifications',
    status: 'In Progress',
    priority: 'Medium',
    assignee: 'Alice Chen',
    dueDate: '2026-06-13',
    estimatedHours: 10,
    completedHours: 3,
    tags: ['frontend', 'notifications'],
    description: 'Web Push API with service worker for background task alerts.',
    isBlocked: false,
  },
  {
    id: 99,
    title: 'Create admin impersonation tool',
    status: 'In Review',
    priority: 'High',
    assignee: 'Eve Johnson',
    dueDate: '2026-05-28',
    estimatedHours: 8,
    completedHours: 8,
    tags: ['admin', 'auth', 'backend'],
    description: 'Allow support staff to impersonate users with full audit trail.',
    isBlocked: false,
  },
  {
    id: 100,
    title: 'Ship v1.0 public launch',
    status: 'Todo',
    priority: 'Critical',
    assignee: 'Carlos Silva',
    dueDate: '2026-07-15',
    estimatedHours: 20,
    completedHours: 0,
    tags: ['release', 'devops', 'milestone'],
    description: 'Coordinate final QA, marketing launch, and production deployment.',
    isBlocked: true,
  },
];
